AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-eks-helm-deployment
    Description: "Deploy helm"
    Author: Florian Kasper
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['eks','aws-auth','ConfigMap','hook']
    HomePageUrl: https://github.com/tomeys
    SemanticVersion: 3.0.0
    SourceCodeUrl: https://github.com/tomeys
    
Parameters:
  ClusterName:
    Type: String
    Default: default
  FunctionName:
    Type: String
    Default: defaultFunc
  LambdaRoleArn:
    Type: String
    
Transform: AWS::Serverless-2016-10-31
Description: Amazon EKS Helm Deployment
Resources:
  lambdalayerkubectl:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl
        SemanticVersion: 2.0.0
      Parameters: 
        LayerName: layer-eks-kubectl-layer-stack
  Func:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: main
      CodeUri: ./func.d
      Runtime: provided
      Layers:
        # - !Ref lambdalayerkubectl
        - !Sub "arn:aws:lambda:eu-central-1:${AWS::AccountId}:layer:layer-eks-kubectl-layer-stack:1"
      MemorySize: 512
      Environment:
        Variables:
          cluster_name: !Ref ClusterName
          aws_account_id: !Sub "${AWS::AccountId}"
          lambda_role_arn: !Ref LambdaRoleArn
      Policies:
         - AWSLambdaBasicExecutionRole
      # Role: !GetAtt LambdaExecutionRole.Arn
      Role: !Ref LambdaRoleArn
      Timeout: 300
  # Deploy21:
  #   Type: Custom::Deploy
  #   Properties:
  #     ServiceToken: !GetAtt Func.Arn
  # UpdateCM:
  #   Type: Custom::UpdateConfigMap
  #   Properties:
  #     ServiceToken: !GetAtt Func.Arn


Outputs:
  LambdaFuncArn:
    Description: Lambda Func ARN
    Value: !GetAtt Func.Arn
  LambdaFuncName:
    Description: Lambda Func Name
    Value: !Ref Func
  LambdaRoleArn:
    Description: Lambda Role ARN
    Value: !Ref LambdaRoleArn
    # Value: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEKSAdminRole"
  # ResultData:
  #   Description: response of the custom resource
  #   Value: !GetAtt UpdateCM.Result
      